replicaCount: 2

image:
  repository: ghcr.io/nolet7/easybanking-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: backend-db-secret
        key: url

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: backend.easybanking.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
